# mysql
mysql:
  host: localhost
  port: 3306
  username: root
  password: password
  database: yogurt

# redis
redis:
  host: 127.0.0.1
  port: 6379
  password: password
  database: 0


# 应用本地
app:
  server-port: 8060
  server-address: localhost
  context-path: /dev
  log-root-level: debug
  log-package-level: debug
  swagger-enable: true # 是否打开swagger
  create-out-conf: false  # 启动是否创建外置配置文件